### ISSUE TITLE
Tela de Login

### ISSUE THREAD

**Issue by tbzambe** [Queline-project/source#1]
Precisamos de uma tela de login.

Assim como a @co-ana falou, uma bem simples, parecida com a do blog acadêmico, com um formulariozinho com `matrícula`, `senha`, botão `entrar`.

No caso da pessoa ter esquecido a senha ou não ter uma ainda, ela teria que fazer a alteração direto no site da faculdade mesmo; será que devemos omitir essas opções ou apenas redirecionar o usuário para a página externa?

**Comment by ramonpenna19** [comment]
Acho que redirecionar para o site da uvv (em outra aba) seria o ideal, já que seria a mesma funcionalidade e se vc pensar que o usuário já veio logado do aluno.uvv.br, ele entraria no sistema de monitoria direto.

**Comment by tbzambe** [comment]
Brincando com layout no meio da noite, opinem pls:

Pensei em deixar o formulário aberto em vez de dentro da caixinha branca para ficar mais simplificado e não sofrer com área de respiro em telas menores. Lembrei também da opção de manter-se conectado que seria uma boa (isso rola, @Queline-project/back?) por questões de usabilidade.

| Sem interação | Com interação | Arquivo aberto |
| --- | --- | --- |
| ![hermes-interacao-off](https://cloud.githubusercontent.com/assets/12170868/14007385/e8c37dda-f154-11e5-843a-d28809b8e4b5.jpg) | ![hermes-interacao-on](https://cloud.githubusercontent.com/assets/12170868/14007379/df29d652-f154-11e5-9bb9-796b119ce1e7.jpg) | ![hermes-editavel](https://cloud.githubusercontent.com/assets/12170868/14007511/2b8cc4d6-f156-11e5-9f9b-d2a4a13a331e.png) |

Cores:
![paleta](https://cloud.githubusercontent.com/assets/12170868/14007716/fcf78f8c-f157-11e5-96f1-97323aebe7de.png)

Fiz uma logo simples apenas para simulação, já que não precisamos colocar a logo da UVV no nosso produto e provavelmente todos nós gostaríamos de evitar isso ao máximo... confio em @co-ana para vir com algo maneiro :100:

**Comment by ramonpenna19** [comment]
Opiniões:
1. Sobre formulário aberto ou fechado em box, por mim tanto faz, isso depende apenas de vocês...
2. Sobre manter o usuário conectado, acho desnecessário, pois nem a uvv implementou isso e acredito que nosso projeto deva ficar o mais simples possível, pois quanto mais detalhes adicionarmos, maior a chance de deixarmos algo errado e perdemos ponto por causa disso. Mas pensando no lado do desenvolvimento, nunca fiz isso, mas acho que consigo fazer.
3. Sobre a logo, gostei da última assim como gostei dessa... acho que isso é outra coisa que não faz diferença. Não vejo porque evitar a logo da UVV "ao máximo", mas por mim realmente tanto faz.

**Comment by ramonpenna19** [comment]
Ah... outra opinião....
Acho que estamos nos preocupando com detalhes realmente desnecessários no momento.
Nós já temos uma tela pronta, funcionando e realmente bonita... não acho legal ficarmos mudando assim, pois se houverem mudanças novas, tanto de layout quanto de funcionalidade pra cada página, esse projeto não sai esse ano...

**Comment by tbzambe** [comment]
Então deixa como tá.

**Comment by co-ana** [comment]
Tatá, curti o novo layout. Farei as alterações agora.
Você pode me mandar a logo? 
Outra coisa: a logo grande fará parte do layout? (Essa foi a única parada que eu não curti haha)

**Comment by ddcosme** [comment]
"manter-se conectado": não tem necessidade para o projeto inicial; se todos concordarem, podemos colocar depois que a maratona for finalizada.

**Comment by ddcosme** [comment]
Por enquanto vamos nos preocupar com as funcionalidades obrigatórias

**Comment by tbzambe** [comment]
@co-ana:

> a logo grande fará parte do layout? (Essa foi a única parada que eu não curti haha)

Tudo aquilo é só sugestão, a logona coloquei ali porque achei meio vazio. Se quiser pode usar daquilo o que achar interessante, e tira fora o que não gostar. A logo tá como symbol no aquivo aberto, mas tó aqui o vetor pra facilitar (não sou boa nisso, tá meio torta):

![logo-teste fw](https://cloud.githubusercontent.com/assets/12170868/14048120/eff77f52-f28a-11e5-9806-e4b6137f0880.png)
