### ISSUE TITLE
Tela inicial

### ISSUE THREAD

**Issue by tbzambe** [Queline-project/source#2]
Esboço da tela inicial do aplicativo, após login do usuário. Contendo áreas para:
- Nome do usuário
- Notificações
- Próxima aula agendada
- Agendar aula / buscar matéria
- **Fazer logout**
- Outras?

Por enquanto, basta que seja uma página mais ou menos organizada, mas é imprescindível que ao menos a opção de fazer logout esteja estabelecida e completamente funcional.

**Comment by ramonpenna19** [comment]
Sim, façam apenas o visual.
No notebook da ana, eu já fiz as funcionalidades de login e logout, depois veja com ela pra vcs já utilizarem esses arquivos.

**Comment by co-ana** [comment]
Se tiver outras paradas para exibir na tela inicial, seria interessante avisar logo :D
Pra facilitar o desenvolvimento do conteúdo principal, é bacana já saber oq será exibido, pra não ter que refazer código.

O menu lateral está quase pronto. Só falta ajustar margin/padding e acrescentar os ícones. 

### Estou em dúvida numa parada: será necessário exibir o curso, turno e matrícula (no menu lateral)?

A Logo dará um pequeno probleminha. Por enquanto, a melhor solução que encontrei foi retirar a parte escrita do "hermes acadêmico" e só deixar o ícone. Se alguém encontrar uma solução melhor, só me falar que eu altero =)

**Comment by co-ana** [comment]
Gente, tou fazendo o conteúdo da main, e surgiu a dúvida: seguiremos o padrão de títulos da UVV?
Há realmente a necessidade de colocar o nome da sessão como um título também? Já que ela fica ativa na "sidebar"? 

Poderiamos colocar somente no mobile, sei lá. rs

## Hermes - não seguindo padrão

![hermes-no-header](https://cloud.githubusercontent.com/assets/17653421/14465161/4fe7e6a6-00a8-11e6-9efc-ae86f15c32d5.JPG)

## Hermes - seguindo padrão uvv

![hermes-with-header](https://cloud.githubusercontent.com/assets/17653421/14465238/8f857b70-00a8-11e6-8ba1-c87c07c68e05.JPG)

## UVV

![uvv-header](https://cloud.githubusercontent.com/assets/17653421/14465098/0d7a7388-00a8-11e6-9840-a3aa44ec65ac.JPG)

**Comment by co-ana** [comment]
Com a ideia inicial, teremos os seguintes boxes na main:
- Notificações;
- Próxima aula agendada;
- Agendar aula;
- Buscar matéria;

Nesse primeiro momento, devemos pensar qual será o conteúdo dessas paradas e como ele será exibido.

Seguem minhas ideias:

### Box de notificação: Uma tabelinha col-6
1. Nova mensagem (Se tiver chat entre aluno x monitor)
2. ?????

### Box - Aula agendada: Uma tabelinha col-6
1. Confirmação do agendamento de aula
2. Se o monitor desmarcou a aula
3. Se o monitor adiou a aula

### Box - Monitores: uma tabela maior (col-12?)

Busca monitores que estão dando aulas das matérias que o aluno está matriculado.
1. Exibe foto do monitor, nome, matéria, curso, período, blablabla

Sites úteis: 
http://themicon.co/theme/angle/v3.3.1/backend-jquery/app/dashboard_v3.html#/
http://webapplayers.com/inspinia_admin-v2.5/

Por favor, deem sugestões também. =)

**Comment by co-ana** [comment]
Possíveis inspirações:
http://www.keenthemes.com/preview/metronic/theme/admin_3/
http://flatfull.com/themes/angulr/html/index.html
http://pages.revox.io/dashboard/latest/html/portlets.html

Esse é SENSACIONAL:
http://www.keenthemes.com/preview/metronic/theme/admin_1/dashboard_3.html
Principalmente na parte de Quick Actions, para facilitar a vida do monitor =D
